minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
blockExoticSubdeps: false
nodeLinker: hoisted
allowBuilds:
  '@google/genai': true
  '@mongodb-js/zstd': false
  fs-xattr: true
  macos-alias: true
  node-liblzma: false
  protobufjs: true
