export const IPC_CHANNELS = {
  cancelAgent: 'agent:cancel',
  agentEvent: 'agent:event',
  startAgentPrompt: 'agent:start-prompt',
  getAgentConfiguration: 'agent:get-configuration',
  removeAgentCredential: 'agent:remove-credential',
  setAgentApiKey: 'agent:set-api-key',
  createProjectDirectory: 'project:create-directory',
  selectProjectDirectory: 'project:select-directory',
  refreshProject: 'project:refresh',
  projectChanged: 'project:changed',
  projectWatcherStatusChanged: 'project:watcher-status-changed',
  copyEditorSelection: 'editor:copy-selection',
  cutEditorSelection: 'editor:cut-selection',
  pasteIntoEditor: 'editor:paste',
  selectAllEditorText: 'editor:select-all',
  saveProjectDocument: 'project:save-document',
  confirmCloseUnsavedDocument: 'editor:confirm-close-unsaved',
  getAppSettings: 'settings:get',
  updateAppSettings: 'settings:update',
  setWindowDirty: 'window:set-dirty',
  windowCloseRequested: 'window:close-requested',
  completeWindowClose: 'window:complete-close',
} as const;
