export const IPC_CHANNELS = {
  cancelAgent: "agent:cancel",
  applyAgentProposal: "agent:apply-proposal",
  agentEvent: "agent:event",
  startAgentPrompt: "agent:start-prompt",
  getAgentConfiguration: "agent:get-configuration",
  removeAgentCredential: "agent:remove-credential",
  setAgentApiKey: "agent:set-api-key",
  updateAgentModelOverride: "agent:update-model-override",
  rejectAgentProposal: "agent:reject-proposal",
  createProjectDirectory: "project:create-directory",
  restoreLastProject: "project:restore-last",
  selectProjectDirectory: "project:select-directory",
  refreshProject: "project:refresh",
  projectChanged: "project:changed",
  projectWatcherStatusChanged: "project:watcher-status-changed",
  copyEditorSelection: "editor:copy-selection",
  cutEditorSelection: "editor:cut-selection",
  pasteIntoEditor: "editor:paste",
  selectAllEditorText: "editor:select-all",
  saveProjectDocument: "project:save-document",
  confirmCloseUnsavedDocument: "editor:confirm-close-unsaved",
  getAppSettings: "settings:get",
  updateAppSettings: "settings:update",
  setWindowDirty: "window:set-dirty",
  windowCloseRequested: "window:close-requested",
  completeWindowClose: "window:complete-close",
} as const;
