export const IPC_CHANNELS = {
  cancelAgent: 'agent:cancel',
  agentEvent: 'agent:event',
  startAgentPrompt: 'agent:start-prompt',
  selectProjectDirectory: 'project:select-directory',
  refreshProject: 'project:refresh',
  projectChanged: 'project:changed',
  projectWatcherStatusChanged: 'project:watcher-status-changed',
  showEditorContextMenu: 'editor:show-context-menu',
  saveProjectDocument: 'project:save-document',
  confirmCloseUnsavedDocument: 'editor:confirm-close-unsaved',
  getAppSettings: 'settings:get',
  updateAppSettings: 'settings:update',
  setWindowDirty: 'window:set-dirty',
  windowCloseRequested: 'window:close-requested',
  completeWindowClose: 'window:complete-close',
} as const;
